// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: deffect-project

#include "../ui.h"

// COMPONENT btnFail

lv_obj_t * ui_btnFail_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_btnFail;
    cui_btnFail = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_btnFail, 100);
    lv_obj_set_height(cui_btnFail, 50);
    lv_obj_set_x(cui_btnFail, 4);
    lv_obj_set_y(cui_btnFail, 173);
    lv_obj_set_align(cui_btnFail, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_btnFail, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_btnFail, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BTNFAIL_NUM);
    children[UI_COMP_BTNFAIL_BTNFAIL] = cui_btnFail;
    lv_obj_add_event_cb(cui_btnFail, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_btnFail, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_btnFail_create_hook(cui_btnFail);
    return cui_btnFail;
}

