// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: deffect-project

#ifndef _UI_COMP_BTNFAIL_H
#define _UI_COMP_BTNFAIL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT btnFail
#define UI_COMP_BTNFAIL_BTNFAIL 0
#define _UI_COMP_BTNFAIL_NUM 1
lv_obj_t * ui_btnFail_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
