// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: deffect-project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_lblSerialNumber = NULL;
lv_obj_t * ui_txtSerialNumber = NULL;
lv_obj_t * ui_btnFail = NULL;
lv_obj_t * ui_lblFailBtnText = NULL;
lv_obj_t * ui_lblIPAddress = NULL;
lv_obj_t * ui_ButtonContainer = NULL;
lv_obj_t * ui_Keyboard4 = NULL;
lv_obj_t * ui_btnRefresh = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_txtSerialNumber(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblSerialNumber = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblSerialNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSerialNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSerialNumber, -148);
    lv_obj_set_y(ui_lblSerialNumber, -186);
    lv_obj_set_align(ui_lblSerialNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSerialNumber, "S/N:");
    lv_obj_set_style_text_font(ui_lblSerialNumber, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtSerialNumber = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_txtSerialNumber, 244);
    lv_obj_set_height(ui_txtSerialNumber, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_txtSerialNumber, 6);
    lv_obj_set_y(ui_txtSerialNumber, -184);
    lv_obj_set_align(ui_txtSerialNumber, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtSerialNumber, "Enter Serial Number");
    lv_textarea_set_one_line(ui_txtSerialNumber, true);

    ui_btnFail = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_btnFail, 222);
    lv_obj_set_height(ui_btnFail, 62);
    lv_obj_set_x(ui_btnFail, 10);
    lv_obj_set_y(ui_btnFail, 199);
    lv_obj_set_align(ui_btnFail, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnFail, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnFail, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnFail, lv_color_hex(0xDD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnFail, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnFail, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_btnFail, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_btnFail, 1, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_btnFail, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_ofs_x(ui_btnFail, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_ofs_y(ui_btnFail, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_lblFailBtnText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblFailBtnText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFailBtnText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFailBtnText, 11);
    lv_obj_set_y(ui_lblFailBtnText, 197);
    lv_obj_set_align(ui_lblFailBtnText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblFailBtnText, "Fail");
    lv_obj_set_style_text_color(ui_lblFailBtnText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblFailBtnText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblFailBtnText, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblIPAddress = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblIPAddress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblIPAddress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblIPAddress, -321);
    lv_obj_set_y(ui_lblIPAddress, 218);
    lv_obj_set_align(ui_lblIPAddress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblIPAddress, "IP ADDRESS");
    lv_obj_set_style_text_font(ui_lblIPAddress, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblIPAddress, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblIPAddress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_lblIPAddress, lv_color_hex(0x110101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_lblIPAddress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonContainer = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonContainer, 692);
    lv_obj_set_height(ui_ButtonContainer, 286);
    lv_obj_set_x(ui_ButtonContainer, -1);
    lv_obj_set_y(ui_ButtonContainer, 8);
    lv_obj_set_align(ui_ButtonContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ButtonContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ButtonContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_Keyboard4 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard4, 772);
    lv_obj_set_height(ui_Keyboard4, 276);
    lv_obj_set_x(ui_Keyboard4, 1);
    lv_obj_set_y(ui_Keyboard4, 6);
    lv_obj_set_align(ui_Keyboard4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_btnRefresh = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_btnRefresh, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2129918560, NULL);
    lv_imgbtn_set_src(ui_btnRefresh, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_2129918560, NULL);
    lv_obj_set_width(ui_btnRefresh, 50);
    lv_obj_set_height(ui_btnRefresh, 50);
    lv_obj_set_x(ui_btnRefresh, 351);
    lv_obj_set_y(ui_btnRefresh, 200);
    lv_obj_set_align(ui_btnRefresh, LV_ALIGN_CENTER);
    lv_obj_set_style_shadow_color(ui_btnRefresh, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_btnRefresh, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_btnRefresh, 1, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_btnRefresh, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_ofs_x(ui_btnRefresh, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_ofs_y(ui_btnRefresh, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_txtSerialNumber, ui_event_txtSerialNumber, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard4, ui_txtSerialNumber);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_lblSerialNumber = NULL;
    ui_txtSerialNumber = NULL;
    ui_btnFail = NULL;
    ui_lblFailBtnText = NULL;
    ui_lblIPAddress = NULL;
    ui_ButtonContainer = NULL;
    ui_Keyboard4 = NULL;
    ui_btnRefresh = NULL;

}
