// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: deffect-project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_lblSerialNumber;
extern void ui_event_txtSerialNumber(lv_event_t * e);
extern lv_obj_t * ui_txtSerialNumber;
extern lv_obj_t * ui_btnFail;
extern lv_obj_t * ui_lblFailBtnText;
extern lv_obj_t * ui_lblIPAddress;
extern lv_obj_t * ui_ButtonContainer;
extern lv_obj_t * ui_Keyboard4;
extern lv_obj_t * ui_btnRefresh;
extern lv_obj_t * ui_lblSelectedDeffectCode;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

